"""Changed username to email for User model

Revision ID: f9d661d1c27b
Revises: 368d8f610ca5
Create Date: 2025-05-26 16:55:14.571070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d661d1c27b'
down_revision = '368d8f610ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint("uq_user_email", ['email'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint("uq_user_email", type_='unique')
        batch_op.create_unique_constraint("uq_user_username", ['username'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###
